### ISSUE TITLE
Hello; how can I display the results of the following operations using fzf-lua?

### ISSUE THREAD

**Issue by whxcode** [ibhagwan/nvim-lua#11]
Hello; how can I display the results of the following operations using fzf-lua?

Because when I select different references; I also want to preview some of the code areas there.

<img width="805" alt="image" src="https://github.com/ibhagwan/nvim-lua/assets/44012914/f1814236-1840-4ee0-a98c-52b031082fa8">

**Comment by ibhagwan** [comment]
Have you tried the `<leader>l..` mappings?

I personally really like `<leader>ll` as it combines all LSP locations:

https://github.com/ibhagwan/nvim-lua/blob/d2292418dc5ace0c11dde1f54f28f64ac748bc47/lua/plugins/fzf-lua/mappings.lua#L130-L151

**Comment by whxcode** [comment]
Thank you; according to the configuration; it is really convenient to use
