### ISSUE TITLE
I can't format the lua file successfully.

### ISSUE THREAD

**Issue by whxcode** [ibhagwan/nvim-lua#12]
If I use the shortcut key gq format, the file in lua format will prompt an error.
But I have installed the corresponding language service through Mason.

<img width="1437" alt="image" src="https://github.com/ibhagwan/nvim-lua/assets/44012914/c6a1818f-4137-43ba-a7c6-8437d4156078">

<img width="924" alt="image" src="https://github.com/ibhagwan/nvim-lua/assets/44012914/8366f6ac-a944-4062-96d8-16231e9d57f7">

I run NullLsLog and get the following error, how can I fix this error?

<img width="1405" alt="image" src="https://github.com/ibhagwan/nvim-lua/assets/44012914/be07f207-f384-4b80-af9b-6ed46affde5f">

and NullLsInfo.

<img width="1202" alt="image" src="https://github.com/ibhagwan/nvim-lua/assets/44012914/81c86e5c-d00d-4636-8d14-9ce414a8cacd">

**Comment by ibhagwan** [comment]
I don't use luaformatter, I use `lua_ls` to format lua files it shouldn't attempt to use `null-ls` to format lua files unless you attempted to further customize this repo.

**Comment by whxcode** [comment]
> I don't use luaformatter, I use `lua_ls` to format lua files it shouldn't attempt to use `null-ls` to format lua files unless you attempted to further customize this repo.

Then how should I configure; to enable the language service that has been followed; to be able to format the current file.

**Comment by ibhagwan** [comment]
> > I don't use luaformatter, I use `lua_ls` to format lua files it shouldn't attempt to use `null-ls` to format lua files unless you attempted to further customize this repo.
> 
> Then how should I configure; to enable the language service that has been followed; to be able to format the current file.

This repo us is just my personal neovim configuration not a neovim distribution like AstroNvim, NvChad, etc, if it doesn’t work or you need extra customization you will need to understand the configuration, find the issue and solve it.

Sorry I can’t be of more help but this repo isn’t a “plugin”, if someone wants to use this repo they should fork it and make their own configuration out of it.

**Comment by ibhagwan** [comment]
I will disable issues on this repo as it’s not meant to be used a neovim distro.
