### ISSUE TITLE
Neovim 0.6.1 compatibility issue

### ISSUE THREAD

**Issue by melsiir** [ibhagwan/nvim-lua#4]
I use your feline config for my nvim config but after updating nevim to 0.6.1 I start get error 

That say vim.lsp.dignostic.get_count is deprecated so I replace it with vim.diagnostics.get()

But start to get this error:

Feline: error while processing component number 1 on section 3 of type 'active': ...rmux/files/usr/share/nvim/runtime/lua/vim/diagnostic.lua:716: opts: expected t
able, got string

Can you please update the config 🙏

**Comment by ibhagwan** [comment]
`feline` hasn't been used in my config for a while, was [replaced by lualine](https://github.com/ibhagwan/nvim-lua/blob/main/lua/plugins/statusline.lua) I just forgot to remove the `feline.lua` file.

Removed in the latest commit https://github.com/ibhagwan/nvim-lua/commit/ec09afd1229ae73227c8b5dd57ad12419c269670
