### ISSUE TITLE
don't find the virtualenv directory

### ISSUE THREAD

**Issue by testfailagain** [ibhagwan/nvim-lua#5]
Hi,

Maybe I'm wrong and it's not a bug but just a feature that isn't there. But I had an old configuration with jedi-vim that automatically finds the virtualenv, so, in my projects I don't see error importing, for example, django libraries. But with this configuration I see all the import zone in red:
Pyright: Import "djangoconf" could not be resolved
Pyright: Import "django.db.models" could not be resolved
etc...

It have another proglem, that I can't use, for example, the gotodefinition.

Is it normal, or maybe I forget to do something (I'm starting with neovim-lua).

**Comment by testfailagain** [comment]
Hi again, I have tried to use 'vim.g.python3_host_prog' pointint to my venv python file
`vim.g.python3_host_prog='/home/bla/venv/bin/python'`
But still isn't working

**Comment by ibhagwan** [comment]
I’m not using python much so I didn’t experience this issue but based on your description it seems to be something related to the configuration of `pyright`:

From https://github.com/microsoft/pyright/issues/2257#issuecomment-912084249:

>By default, pyright assumes that the top directory of your project is in your import resolution path list. Other directories are not used as search roots unless you configure them as such.
>You are importing from common, but this directory isn't at the top level of your project, so it can't be resolved.
>If your intent is for stuff to be used as a root directory for import resolution, you can add it to the extraPaths setting in the pyrightconfig.json configuration file.
