### ISSUE TITLE
Matching fzf-lua's preview screen

### ISSUE THREAD

**Issue by hqkhan** [ibhagwan/nvim-lua#6]
Hello! Cool setup overall. I wanted to ask how I can match my fzf-lua's preview window's theme to my current theme. The way mine looks is this:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22674069/181937591-a831af54-8f6f-412f-bb50-73f0e9e18dd3.png">

The theme in code is correct but not the left side or where the files populate. How do I get them to match?

**Comment by ibhagwan** [comment]
Left side colors are controlled by fzf, you can set the highlights using `fzf_colors` which accepts neovim highlights. `man fzf` to see all available highlight options as the README `fzf_colors` doesn’t contain all of them:
```
COLOR NAMES:
   fg         Text
   bg         Background
   preview-fg Preview window text
   preview-bg Preview window background
   hl         Highlighted substrings
   fg+        Text (current line)
   bg+        Background (current line)
   gutter     Gutter on the left (defaults to bg+)
   hl+        Highlighted substrings (current line)
   query      Query string
   disabled   Query string when search is disabled
   info       Info line (match counters)
   border     Border around the window ([--border](https://www.mankier.com/1/fzf#--border) and [--preview](https://www.mankier.com/1/fzf#--preview))
   prompt     Prompt
   pointer    Pointer to the current line
   marker     Multi-select marker
   spinner    Streaming input indicator
   header     Header
```

**Comment by hqkhan** [comment]
Thank you for that. I had one more question about devicons. The size on mine is small compared to yours + the coloring is a bit strange as well. Is that also due to coloring?

**Comment by ibhagwan** [comment]
> Thank you for that. I had two questions.
> 
> 1. Devicons -- The size on mine is small compared to yours. Do you know if I can modify that via some config?
> 2. I love the way your cursorline looks with the black background on the line you're at. How did you achieve that? I shamefully (xD) took your lua-embark colorscheme but it didn't have the cursor black background. Was wondering if that's just because it's not updated or if there's something special.

Oops I missed this follow up :)

1. This is font dependent, you’re probably using a monospaced nerd font, use the non-monospaced version for the larger icons.

2. That’s controlled by `fzf_colors`, you need to set `bg+` to `CursorLine`:
https://github.com/ibhagwan/nvim-lua/blob/6583f809c1c47c5ae6661c050deccd689787b342/lua/plugins/fzf-lua/init.lua#L25-L39

**Comment by hqkhan** [comment]
Oh no worries at all. #1 makes sense! Yeah I had forgotten to `set cursorline` in my settings. I'm all good now. Thanks!
