### ISSUE TITLE
Delta config

### ISSUE THREAD

**Issue by hqkhan** [ibhagwan/nvim-lua#7]
Apologies to keep bothering you. I was in the middle of configuring delta and wanted to reference your delta config but I couldn't find it here nor in `dotfiles` repo. Is it not on github or do you not have it configured much? The colors when it comes to the diff were hard to read.

**Comment by ibhagwan** [comment]
I don’t have any special configuration for delta, I just use the defaults, I would assume the colors are coming from the terminal colors configured by the neovim colorscheme, custom colors for delta are on my TODO list but haven’t had the chance yet.

**Comment by hqkhan** [comment]
Sounds good!
