### ISSUE TITLE
[help] dap event is not triggered

### ISSUE THREAD

**Issue by yyy33** [ibhagwan/nvim-lua#8]
Hi, I used your osv configuration file and I have several event listeners, but when I execute lua require'dap'.terminate(), dap-ui is not closed,

```
dap.listeners.after.event_initialized["dapui_config"] = function()
  dapui.open()
end
dap.listeners.before.event_terminated["dapui_config"] = function()
  dapui.close()
end
dap.listeners.before.event_exited["dapui_config"] = function()
  dapui.close()
end
```

**Comment by ibhagwan** [comment]
It all depends on what language you're debugging, if you're debugging lua [there's never a terminate](https://github.com/jbyuki/one-small-step-for-vimkind/issues/13), if it's not lua I have no idea why or if it's supposed to fire, you're better off opening an issue with the `dap` plugin repo.

**Comment by yyy33** [comment]
> It all depends on what language you're debugging, if you're debugging lua [there's never a terminate](https://github.com/jbyuki/one-small-step-for-vimkind/issues/13), if it's not lua I have no idea why or if it's supposed to fire, you're better off opening an issue with the `dap` plugin repo.

Thank you.
