### ISSUE TITLE
`.editorconfig` questions

### ISSUE THREAD

**Issue by CharlesChiuGit** [ibhagwan/nvim-lua#9]
Sorry for the late reply, I was quite busy in the past few days. I know sumneko_lua can auto-detect `.luarc.json`, but I didn't see where does `.editorconfig` been passed, and it's not taking effect on my code too. Do u mind explain a bit on how does it works?

Thanks!

**Comment by ibhagwan** [comment]
It's all explained here: https://github.com/sumneko/lua-language-server/wiki/Formatter

**Comment by CharlesChiuGit** [comment]
Thanks! Let me take a look!
